### ISSUE TITLE
Are bot git in memory and git fs the same (irmin-git)?

### ISSUE THREAD

**Issue by tcoopman** [zshipko/irmin-tutorial#2]
I was a bit surprised to see `irmin-git` twice for both in mem and fs:
 
> a git-compatible in-memory store (irmin-git) and a git-compatible filesystem store (irmin-git).

Is that a typo, or is it correct? If it's correct, it might be good to point that out?

**Comment by zshipko** [comment]
Hey, thanks for pointing this out. It is actually correct — they are both part of irmin-git, but I will work on the wording here to explain that better.

**Comment by zshipko** [comment]
Fixed here: https://github.com/zshipko/irmin-tutorial/commit/ae044c9bc3e23274ea0e5434af6d2456ec4eb1a3

Thanks!
